services:
  - type: web
    name: corrida-presidencia-live
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TIKTOK_USERNAME
        value: denilsonnunesss
